// Generates typed `as const` ABIs from Foundry artifacts (contracts/out). Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "..", "contracts", "out");
const dest = join(here, "..", "src", "abis");
const contracts = [
  ["UnisonExchange", "unisonExchangeAbi"],
  ["OperatorSignedReference", "operatorSignedReferenceAbi"],
  ["LiquidityVault", "liquidityVaultAbi"],
  ["ChainlinkReference", "chainlinkReferenceAbi"],
  ["ChainlinkCausalReference", "chainlinkCausalReferenceAbi"],
  ["LatencyChallenge", "latencyChallengeAbi"],
  ["ChallengeAccount", "challengeAccountAbi"],
  ["PythReference", "pythReferenceAbi"],
  ["ManualReference", "manualReferenceAbi"],
  ["OrderGateway", "orderGatewayAbi"],
];
const index = [];
for (const [name, ident] of contracts) {
  const art = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
  const body = `// Generated by scripts/gen-abis.mjs from contracts/out — do not edit.\nexport const ${ident} = ${JSON.stringify(art.abi, null, 2)} as const;\n`;
  writeFileSync(join(dest, `${name}.ts`), body);
  index.push(`export { ${ident} } from "./${name}.ts";`);
}
writeFileSync(join(dest, "index.ts"), index.join("\n") + "\n");
console.log(`wrote ${contracts.length} ABIs to ${dest}`);
