/**
 * Builds every brand asset from the mark geometry (scripts/brand/mark.mjs) and the outlined wordmark
 * (`GEOMETRY_ONLY=1` writes just the two generated modules for React and stops before the rasters):
 *
 *   public/brand/*.svg|png       downloads for the /brand page and press
 *   app/icon.svg                 favicon (16 px master; blued-steel ball, lume ball in dark browser chrome)
 *   app/favicon.ico              16/32/48 for legacy agents
 *   app/apple-icon.png           180 px, opaque onyx dial
 *   public/icons/*.png           PWA icons incl. maskable (opaque, full bleed, art inside the safe zone)
 *   components/brand/geometry.ts mark path data for the live React components (generated; do not edit)
 *   components/brand/glyphs.ts   the outlined wordmark and the lockup's placement of the mark (generated)
 *
 *   node scripts/brand/build.mjs
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { chromium } from "@playwright/test";
import { formatHex } from "culori";
import { BALL, emblem, emblemSvg } from "./emblem.mjs";
import { MARK, MARK_MID, MARK_SMALL } from "./mark.mjs";
import { CAP, lockupSvg, markInWordmarkUnits, UPM, wordmark, wordmarkSvg } from "./wordmark.mjs";
import { dialSvg } from "./dial.mjs";

const at = (p) => new URL(`../../${p}`, import.meta.url);
const out = (p, data) => {
  const u = at(p);
  mkdirSync(new URL(".", u), { recursive: true });
  writeFileSync(u, data);
};

const C = {
  porcelain: formatHex("oklch(0.985 0.003 250)"),
  ink: formatHex("oklch(0.19 0.012 262)"),
  onyx: formatHex("oklch(0.135 0.006 265)"),
  pearl: formatHex("oklch(0.95 0.006 250)"),
  lume: formatHex("oklch(0.74 0.085 266)"), // the night accent: blued steel lifted for a black dial
};

// ------------------------------------------------------------------ vector downloads
const finish = { ink: BALL.steel, porcelain: BALL.lume };
for (const [name, ink] of Object.entries({ ink: C.ink, porcelain: C.pearl })) {
  // Monochrome (engraving, single-colour print) and finished (screen) versions.
  out(`public/brand/unison-mark-${name}.svg`, emblemSvg(MARK, { ink, size: 512, title: "Unison" }));
  out(
    `public/brand/unison-mark-${name}-finished.svg`,
    emblemSvg(MARK, { ink, ballFill: finish[name], size: 512, title: "Unison" }),
  );
  out(`public/brand/unison-mark-small-${name}.svg`, emblemSvg(MARK_SMALL, { ink, size: 64, title: "Unison" }));
  out(`public/brand/unison-wordmark-${name}.svg`, wordmarkSvg({ ink }));
  out(`public/brand/unison-lockup-${name}.svg`, lockupSvg(MARK, { ink, gapEm: 0.62, master: "display" }));
}

// ------------------------------------------------------------------ favicon (SVG; flips with the browser's scheme)
const sm = emblem(MARK_SMALL);
const smBody = sm.parts.filter((p) => p.role === "body").map((p) => p.d).join(" ");
const smBall = sm.parts.filter((p) => p.role !== "body").map((p) => p.d).join(" ");
out(
  "app/icon.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><style>.b{fill:${C.ink}}.j{fill:${BALL.steel}}@media (prefers-color-scheme:dark){.b{fill:${C.pearl}}.j{fill:${BALL.lume}}}</style><path class="b" d="${smBody}"/><path class="j" d="${smBall}"/></svg>\n`,
);

// ------------------------------------------------------------------ app icon art
const appIcon = (size, opts = {}) => dialSvg(size, size >= 120 ? MARK : MARK_MID, { ...opts, colors: C });
out("public/brand/unison-app-icon.svg", appIcon(1024));

// ------------------------------------------------------------------ generated geometry for React
const parts = (params) => emblem(params).parts.map(({ d, role }) => ({ d, role }));
const nav = markInWordmarkUnits(MARK_MID);
const wm = Object.fromEntries(
  ["display", "mid", "text"].map((k) => {
    const w = wordmark("UNISON", k);
    return [k, { d: w.glyphs.map((g) => g.d).join(" "), left: w.left, width: w.width, top: w.top, bottom: w.bottom }];
  }),
);
out(
  "components/brand/geometry.ts",
  `/* Generated by scripts/brand/build.mjs from scripts/brand/mark.mjs. Do not edit by hand. */
export interface MarkPart {
  d: string;
  /** "body" fills with ink; "ball" is the resonator ball (the single price point), finished as blued steel or lume. */
  role: "body" | "ball" | "jewel" | "cut";
}
/** Display master (≥ 44 px), 48-unit grid. */
export const MARK_PARTS: readonly MarkPart[] = ${JSON.stringify(parts(MARK))};
export const MARK_BOX = ${JSON.stringify(emblem(MARK).box)} as const;
/** Text master (20–44 px). */
export const MARK_MID_PARTS: readonly MarkPart[] = ${JSON.stringify(parts(MARK_MID))};
export const MARK_MID_BOX = ${JSON.stringify(emblem(MARK_MID).box)} as const;
/** Heavy master (≤ 20 px), snapped to the 16 px grid. */
export const MARK_SMALL_PARTS: readonly MarkPart[] = ${JSON.stringify(parts(MARK_SMALL))};
`,
);
// The wordmark lives apart from the mark, so a page that only animates the fork doesn't carry three wordmarks.
out(
  "components/brand/glyphs.ts",
  `/* Generated by scripts/brand/build.mjs from the outlined wordmark. Do not edit by hand. */
/** Outlined wordmark per optical master: font units, cap top y = 0, baseline y = ${CAP}, ${UPM} units per em. */
export const WORDMARK = ${JSON.stringify(wm)} as const;
export const WORDMARK_CAP = ${CAP};
/** The text-master mark placed in wordmark units: tines on the cap line, bowl on the baseline, stem as a descender. */
export const LOCKUP_MARK = ${JSON.stringify({ scale: nav.scale, width: nav.width, descent: nav.descent, top: emblem(MARK_MID).box.top, R: emblem(MARK_MID).box.R })} as const;
`,
);
if (process.env.GEOMETRY_ONLY === "1") process.exit(0);

// ------------------------------------------------------------------ rasters (PNG + ICO) through Chromium
const browser = await chromium.launch();
const page = await browser.newPage();
async function png(svg, size, file) {
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(
    `<html><body style="margin:0;background:transparent">${svg.replace(/width="\d+" height="\d+"/, `width="${size}" height="${size}"`)}</body></html>`,
  );
  const buf = await page.locator("svg").first().screenshot({ omitBackground: true });
  if (file) out(file, buf);
  return buf;
}
await png(appIcon(180, { maskable: true }), 180, "app/apple-icon.png"); // iOS masks it; opaque, full bleed
await png(appIcon(192), 192, "public/icons/icon-192.png");
await png(appIcon(512), 512, "public/icons/icon-512.png");
await png(appIcon(512, { maskable: true }), 512, "public/icons/icon-maskable-512.png");
await png(appIcon(1024), 1024, "public/brand/unison-app-icon-1024.png");
for (const [name, ink] of Object.entries({ ink: C.ink, porcelain: C.pearl })) {
  await png(
    emblemSvg(MARK, { ink, ballFill: finish[name], size: 1024 }),
    1024,
    `public/brand/unison-mark-${name}.png`,
  );
}

// favicon.ico: PNG entries (16, 32, 48); 16 uses the pixel-snapped master
const icoSizes = [16, 32, 48];
const pngs = [];
for (const s of icoSizes) {
  pngs.push(await png(emblemSvg(s <= 20 ? MARK_SMALL : MARK_MID, { ink: C.ink, ballFill: BALL.steel, size: s }), s));
}
const header = Buffer.alloc(6 + 16 * pngs.length);
header.writeUInt16LE(0, 0);
header.writeUInt16LE(1, 2);
header.writeUInt16LE(pngs.length, 4);
let offset = header.length;
pngs.forEach((b, i) => {
  const e = 6 + 16 * i;
  header.writeUInt8(icoSizes[i] % 256, e);
  header.writeUInt8(icoSizes[i] % 256, e + 1);
  header.writeUInt16LE(1, e + 4);
  header.writeUInt16LE(32, e + 6);
  header.writeUInt32LE(b.length, e + 8);
  header.writeUInt32LE(offset, e + 12);
  offset += b.length;
});
out("app/favicon.ico", Buffer.concat([header, ...pngs]));
await browser.close();
console.log("brand assets built");
