/**
 * Unison Zero: Mona Sans's open zero, set on the tabular width, as a one-glyph face.
 *
 * Mona Sans draws its tabular zero slashed, and has no feature that opens it, so every aligned column read like a
 * terminal ("$18Ø.ØØ") beside open zeros in prose. This builds a tiny face holding only U+0030, from Mona Sans's
 * own open zero, centred on the tabular advance, at each weight and width the interface uses: 400, 500 (exactly
 * between 400 and 600: the outlines share one point structure), 600, and the wide 600 of instrument labels. It is
 * listed first in the sans stack with `unicode-range: U+30`, so the browser takes every "0" from it and everything
 * else from Mona Sans. It lacks a space, so it never sets the line box.
 *
 * Derived from Mona Sans (Copyright 2023 GitHub, Inc., SIL Open Font License 1.1) under its own name, as the
 * licence asks of a modified version; the face is itself under the OFL.
 *
 *   node scripts/brand/zero.mjs      writes app/unison-zero.css
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const web = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const load = (f) => {
  const b = readFileSync(join(web, "assets", "fonts", f));
  return opentype.parse(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
};
const regular = load("MonaSans-400.ttf");
const semibold = load("MonaSans-600.ttf");
const wide = load("MonaSans-Wide-600.ttf");

const tabular = (font) => {
  for (let i = 0; i < font.glyphs.length; i++) if (font.glyphs.get(i).name === "zero.tf") return font.glyphs.get(i).advanceWidth;
  throw new Error("no zero.tf");
};
const zeroOf = (font) => {
  const g = font.charToGlyph("0");
  return { commands: g.path.commands.map((c) => ({ ...c })), advance: g.advanceWidth, tabular: tabular(font) };
};

/** Point-for-point blend of two compatible outlines. */
function blend(a, b, t) {
  if (a.commands.length !== b.commands.length) throw new Error("outlines differ");
  const mix = (p, q) => p + (q - p) * t;
  return {
    commands: a.commands.map((c, i) => {
      const d = b.commands[i];
      if (c.type !== d.type) throw new Error("outlines differ");
      const out = { type: c.type };
      for (const k of ["x", "y", "x1", "y1", "x2", "y2"]) if (k in c) out[k] = mix(c[k], d[k]);
      return out;
    }),
    advance: mix(a.advance, b.advance),
    tabular: mix(a.tabular, b.tabular),
  };
}

function face(zero, style) {
  const dx = (zero.tabular - zero.advance) / 2;
  const path = new opentype.Path();
  for (const c of zero.commands) {
    const m = { ...c };
    for (const k of ["x", "x1", "x2"]) if (k in m) m[k] += dx;
    path.commands.push(m);
  }
  const notdef = new opentype.Glyph({ name: ".notdef", unicode: 0, advanceWidth: zero.tabular, path: new opentype.Path() });
  const glyph = new opentype.Glyph({ name: "zero", unicode: 48, advanceWidth: Math.round(zero.tabular), path });
  const font = new opentype.Font({
    familyName: "Unison Zero",
    styleName: style,
    unitsPerEm: regular.unitsPerEm,
    ascender: regular.ascender,
    descender: regular.descender,
    copyright: "Mona Sans glyph (c) 2023 GitHub, Inc. OFL-1.1",
    glyphs: [notdef, glyph],
  });
  return Buffer.from(font.toArrayBuffer()).toString("base64");
}

const r = zeroOf(regular);
const s = zeroOf(semibold);
const faces = [
  { weight: 400, stretch: "100%", zero: r, style: "Regular" },
  { weight: 500, stretch: "100%", zero: blend(r, s, 0.5), style: "Medium" },
  { weight: 600, stretch: "100%", zero: s, style: "SemiBold" },
  { weight: 600, stretch: "125%", zero: zeroOf(wide), style: "Wide SemiBold" },
];

const css = [
  "/* Generated by scripts/brand/zero.mjs: Mona Sans's open zero on the tabular width, one glyph per face. Do not edit. */",
  "/* Derived from Mona Sans, Copyright 2023 GitHub, Inc., SIL Open Font License 1.1. */",
  ...faces.map(
    (f) => `@font-face {
  font-family: "Unison Zero";
  src: url(data:font/otf;base64,${face(f.zero, f.style)}) format("opentype");
  font-weight: ${f.weight};
  font-stretch: ${f.stretch};
  font-display: block;
  unicode-range: U+30;
}`,
  ),
  "",
].join("\n");
writeFileSync(join(web, "app", "unison-zero.css"), css);
console.log(`app/unison-zero.css: ${faces.length} faces, ${(css.length / 1024).toFixed(1)} KB`);
