// Generated by scripts/gen-abis.mjs from contracts/out — do not edit.
export const chainlinkCausalReferenceAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "feeds",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "base",
        "type": "address",
        "internalType": "contract AggregatorV3Interface"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "contract AggregatorV3Interface"
      },
      {
        "name": "baseDecimals",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "quoteFeedDecimals",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "quoteTokenDecimals",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "maxAgeSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "quoteMaxAgeSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "openSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "closeSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "depegBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "set",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latest",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "observedAt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum IReferenceAdapter.Status"
      },
      {
        "name": "round",
        "type": "uint80",
        "internalType": "uint80"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "read",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "publishTimeMs",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum IReferenceAdapter.Status"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "readAfter",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "afterSec",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "payload",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "observedAt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum IReferenceAdapter.Status"
      },
      {
        "name": "round",
        "type": "uint80",
        "internalType": "uint80"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeed",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "base",
        "type": "address",
        "internalType": "contract AggregatorV3Interface"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "contract AggregatorV3Interface"
      },
      {
        "name": "quoteTokenDecimals",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "maxAgeSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "quoteMaxAgeSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "openSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "closeSec",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "depegBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "FeedSet",
    "inputs": [
      {
        "name": "marketId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "base",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "quoteTokenDecimals",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "maxAgeSec",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "quoteMaxAgeSec",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "openSec",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "closeSec",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "depegBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadAnswer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadQuoteRound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAfterSeal",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotFirstObservation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotYet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ObservationExists",
    "inputs": [
      {
        "name": "round",
        "type": "uint80",
        "internalType": "uint80"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownFeed",
    "inputs": []
  }
] as const;
